#!/bin/sh
[[ -z "$XDG_CONFIG_HOME" ]] && XDG_CONFIG_HOME="$HOME/.config"
cp -pi termite.conf $XDG_CONFIG_HOME/termite/config
cp -pi ncmpcpp/config $HOME/.ncmpcpp/config
cp -pi ncmpcpp/bindings $HOME/.ncmpcpp/bindings
cp -pi tmux.conf $HOME/.tmux.conf
cp -pi emacs.conf $HOME/.emacs
cp -pi fonts.conf $XDG_CONFIG_HOME/fontconfig
cp -pi mpv/mpv.conf $XDG_CONFIG_HOME/mpv/mpv.conf
cp -pi mpv/input.conf $XDG_CONFIG_HOME/mpv/input.conf
cp -pi mpv/scripts/mpvmenulaunch.lua $XDG_CONFIG_HOME/mpv/scripts/mpvmenulaunch.lua

