#!/bin/bash
mydir=`dirname $0`
for i in `ls $mydir/*.css`
do
 style=`basename $i .css`
 read -p "Update style $style in stylish database [y/n]?" yn
 [ $yn = y -o $yn = Y ] &&
  $mydir/../utils/stylish_import_style $style $mydir/$style.css
done
