#!/usr/bin/env python2

import os, os.path, sys, sqlite3
if len(sys.argv)<3:
    print "Usage: %s stylename filename" % sys.argv[0]
    exit()
try: 
    f = open(sys.argv[2])
except:
    print "File %s doesn't exist."
    exit(-1)
data = f.read().decode("utf-8")
style = sys.argv[1].decode("utf-8")
f.close()
ffdir = os.environ['HOME']+"/.mozilla/firefox"
path  = ffdir + "/"
path += filter(lambda i:i.endswith("default"), os.listdir(ffdir))[0]
path += "/stylish.sqlite"
conn = sqlite3.connect(path) 
cur = conn.cursor()
cur.execute("select id from styles where name=?", (style, ))  
tmp = cur.fetchone()
if not tmp:
    print "No style named \"%s\" exists in stylish database. Please create a style with that name and any code using the stylish interface. This script only imports the data to existing styles." % style
    exit(-2)
id = tmp[0]
cur.execute("update styles set code=? where id=?", (data, id))
conn.commit()
conn.close()

