#!/usr/bin/env python2

import os, os.path, sys, sqlite3
if len(sys.argv)<2:
    print "Usage: %s stylename" % sys.argv[0]
    exit()
style = sys.argv[1].decode("utf-8") 
ffdir = os.environ['HOME']+"/.mozilla/firefox"
path  = ffdir + "/"
path += filter(lambda i:i.endswith("default"), os.listdir(ffdir))[0]
path += "/stylish.sqlite"
conn = sqlite3.connect(path) 
cur = conn.cursor()
cur.execute("select code from styles where name=?", (style, ))
tmp = cur.fetchone()
if not tmp:
    print "No style named \"%s\" exists in stylish database." % style
    exit(-1)
sys.stdout.write(tmp[0])
conn.close()

