#!/bin/bash

mydiff() {
    diff -u $2 $1 | sed s/^\+/$'\E[1;32m'\+/ | sed s/^\-/$'\E[1;31m'\-/ | sed s/\$/$'\E[0m'/
}
idiff() {
    mydiff $2 $1
}

[[ -z "$XDG_CONFIG_HOME" ]] && XDG_CONFIG_HOME="$HOME/.config"

cpcmd="cp -pi"
diffcmd="mydiff"
idiffcmd="idiff"

cmd=$cpcmd
help="Use option -d to diff instead of update. Use -D for inverse diff."
n=0
mydir=`dirname $0`
while getopts "hdD" opt
do
 case $opt in
  h) echo -e "$help"; exit 0 ;;
  d) cmd=$diffcmd; let "n++" ;;
  D) cmd=$idiffcmd; let "n++" ;;
 esac
done
while [[ "$n" -gt 0 ]]; do shift; let "n--"; done

for i in `ls $mydir/../stylish/*.css`
do
 styles=(${styles[*]} `basename $i .css`)
done
ricedir=`echo ${1:-$mydir/..} | sed 's_/$__'`
$cmd $XDG_CONFIG_HOME/termite/config $ricedir/misc/termite.conf
$cmd $XDG_CONFIG_HOME/fontconfig/fonts.conf $ricedir/misc/fonts.conf
$cmd $HOME/.tmux.conf $ricedir/misc/tmux.conf
$cmd $HOME/.emacs $ricedir/misc/emacs.conf
$cmd $XDG_CONFIG_HOME/geany/colorschemes/darkmono.conf $ricedir/geany/darkmono.conf
$cmd $XDG_CONFIG_HOME/geany/colorschemes/neon.conf $ricedir/geany/neon.conf
$cmd $HOME/.ncmpcpp/config $ricedir/misc/ncmpcpp/config
$cmd $HOME/.ncmpcpp/bindings $ricedir/misc/ncmpcpp/bindings
$cmd $HOME/.themes/Darkasmysoul/gtk-2.0/gtkrc $ricedir/gtk/Darkasmysoul/gtk-2.0/gtkrc

stylestmpdir=/tmp/styles-$$
mkdir -p $stylestmpdir
for i in ${styles[*]}
do
 $mydir/stylish_export_style $i > $stylestmpdir/$i.css
 $cmd $stylestmpdir/$i.css $ricedir/stylish/$i.css
done
rm -r $stylestmpdir
